version: "3"
volumes:
    db:
services:
  app:
    restart: unless-stopped
    tty: true
    build:
      context: app/.
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    environment:
      DOCUMENTROOT: "public"
    volumes:
      - "./..:/var/www/html"
    ports:
      - ${PORTA_HTTP:-80}:80
      - ${PORTA_HTTPS:-443}:443
    depends_on:
      - db
  db:
    restart: unless-stopped
    tty: true
    build:
      context: db/.
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    environment:
      - "POSTGRES_DB=app"
      - "POSTGRES_USER=app"
      - "POSTGRES_PASSWORD=123456"
    volumes:
        - db:/var/lib/postgresql/data
    ports:
      - ${PORTA_POSTGRESQL:-5432}:5432
  redis:
    restart: unless-stopped
    tty: true
    build:
      context: redis
      dockerfile: Dockerfile
      args:
        - HTTPS_PROXY=${https_proxy:-}
        - HTTP_PROXY=${http_proxy:-}
        - FTP_PROXY=${ftp_proxy:-}
        - NO_PROXY=${no_proxy:-}
    ports:
      - ${PORTA_REDIS:-6379}:6379
